build:
  version: "2.0"

accounts:
  message: "Welcome to the accounts API"
  contactDetails:
    name: "Liliherax - QA Lead"
    email: "__"
  onCallSupport:
    - (011)-GOOD-PLEASE-HELP-TESTING-THIS